// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/SIUE_GroceryStore/pb_msg_grocery.proto

package com.ociweb.pronghorn.stage.generator;

public final class PBSpeedQueryProvider {
  private PBSpeedQueryProvider() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InventoryDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_grocery.InventoryDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 StoreID = 1;</code>
     */
    boolean hasStoreID();
    /**
     * <code>required int32 StoreID = 1;</code>
     */
    int getStoreID();

    /**
     * <code>required int64 Date = 2;</code>
     */
    boolean hasDate();
    /**
     * <code>required int64 Date = 2;</code>
     */
    long getDate();

    /**
     * <code>required string ProductName = 3;</code>
     */
    boolean hasProductName();
    /**
     * <code>required string ProductName = 3;</code>
     */
    java.lang.String getProductName();
    /**
     * <code>required string ProductName = 3;</code>
     */
    com.google.protobuf.ByteString
        getProductNameBytes();

    /**
     * <code>required uint32 Amount = 4;</code>
     */
    boolean hasAmount();
    /**
     * <code>required uint32 Amount = 4;</code>
     */
    int getAmount();

    /**
     * <code>required uint32 recordID = 5;</code>
     */
    boolean hasRecordID();
    /**
     * <code>required uint32 recordID = 5;</code>
     */
    int getRecordID();

    /**
     * <code>optional string Units = 6;</code>
     */
    boolean hasUnits();
    /**
     * <code>optional string Units = 6;</code>
     */
    java.lang.String getUnits();
    /**
     * <code>optional string Units = 6;</code>
     */
    com.google.protobuf.ByteString
        getUnitsBytes();
  }
  /**
   * Protobuf type {@code pb_grocery.InventoryDetails}
   */
  public static final class InventoryDetails extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb_grocery.InventoryDetails)
      InventoryDetailsOrBuilder {
    // Use InventoryDetails.newBuilder() to construct.
    private InventoryDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InventoryDetails(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InventoryDetails defaultInstance;
    public static InventoryDetails getDefaultInstance() {
      return defaultInstance;
    }

    public InventoryDetails getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InventoryDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              storeID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              date_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              productName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              amount_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              recordID_ = input.readUInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              units_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.internal_static_pb_grocery_InventoryDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.internal_static_pb_grocery_InventoryDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails.class, com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails.Builder.class);
    }

    public static com.google.protobuf.Parser<InventoryDetails> PARSER =
        new com.google.protobuf.AbstractParser<InventoryDetails>() {
      public InventoryDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InventoryDetails(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InventoryDetails> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STOREID_FIELD_NUMBER = 1;
    private int storeID_;
    /**
     * <code>required int32 StoreID = 1;</code>
     */
    public boolean hasStoreID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 StoreID = 1;</code>
     */
    public int getStoreID() {
      return storeID_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private long date_;
    /**
     * <code>required int64 Date = 2;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 Date = 2;</code>
     */
    public long getDate() {
      return date_;
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 3;
    private java.lang.Object productName_;
    /**
     * <code>required string ProductName = 3;</code>
     */
    public boolean hasProductName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ProductName = 3;</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ProductName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private int amount_;
    /**
     * <code>required uint32 Amount = 4;</code>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 Amount = 4;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int RECORDID_FIELD_NUMBER = 5;
    private int recordID_;
    /**
     * <code>required uint32 recordID = 5;</code>
     */
    public boolean hasRecordID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 recordID = 5;</code>
     */
    public int getRecordID() {
      return recordID_;
    }

    public static final int UNITS_FIELD_NUMBER = 6;
    private java.lang.Object units_;
    /**
     * <code>optional string Units = 6;</code>
     */
    public boolean hasUnits() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string Units = 6;</code>
     */
    public java.lang.String getUnits() {
      java.lang.Object ref = units_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          units_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Units = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUnitsBytes() {
      java.lang.Object ref = units_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        units_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      storeID_ = 0;
      date_ = 0L;
      productName_ = "";
      amount_ = 0;
      recordID_ = 0;
      units_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStoreID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProductName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRecordID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, storeID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, date_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getProductNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, amount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, recordID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUnitsBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, storeID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, date_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getProductNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, amount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, recordID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUnitsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb_grocery.InventoryDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_grocery.InventoryDetails)
        com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.internal_static_pb_grocery_InventoryDetails_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.internal_static_pb_grocery_InventoryDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails.class, com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails.Builder.class);
      }

      // Construct using com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        storeID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        productName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        recordID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        units_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.internal_static_pb_grocery_InventoryDetails_descriptor;
      }

      public com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails getDefaultInstanceForType() {
        return com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails.getDefaultInstance();
      }

      public com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails build() {
        com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails buildPartial() {
        com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails result = new com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.storeID_ = storeID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.productName_ = productName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.amount_ = amount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.recordID_ = recordID_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.units_ = units_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails) {
          return mergeFrom((com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails other) {
        if (other == com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails.getDefaultInstance()) return this;
        if (other.hasStoreID()) {
          setStoreID(other.getStoreID());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasProductName()) {
          bitField0_ |= 0x00000004;
          productName_ = other.productName_;
          onChanged();
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasRecordID()) {
          setRecordID(other.getRecordID());
        }
        if (other.hasUnits()) {
          bitField0_ |= 0x00000020;
          units_ = other.units_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStoreID()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasProductName()) {
          
          return false;
        }
        if (!hasAmount()) {
          
          return false;
        }
        if (!hasRecordID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ociweb.pronghorn.stage.generator.PBSpeedQueryProvider.InventoryDetails) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int storeID_ ;
      /**
       * <code>required int32 StoreID = 1;</code>
       */
      public boolean hasStoreID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 StoreID = 1;</code>
       */
      public int getStoreID() {
        return storeID_;
      }
      /**
       * <code>required int32 StoreID = 1;</code>
       */
      public Builder setStoreID(int value) {
        bitField0_ |= 0x00000001;
        storeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 StoreID = 1;</code>
       */
      public Builder clearStoreID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        storeID_ = 0;
        onChanged();
        return this;
      }

      private long date_ ;
      /**
       * <code>required int64 Date = 2;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 Date = 2;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>required int64 Date = 2;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 Date = 2;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object productName_ = "";
      /**
       * <code>required string ProductName = 3;</code>
       */
      public boolean hasProductName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string ProductName = 3;</code>
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ProductName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ProductName = 3;</code>
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        productName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ProductName = 3;</code>
       */
      public Builder clearProductName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        productName_ = getDefaultInstance().getProductName();
        onChanged();
        return this;
      }
      /**
       * <code>required string ProductName = 3;</code>
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        productName_ = value;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>required uint32 Amount = 4;</code>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 Amount = 4;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>required uint32 Amount = 4;</code>
       */
      public Builder setAmount(int value) {
        bitField0_ |= 0x00000008;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 Amount = 4;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        amount_ = 0;
        onChanged();
        return this;
      }

      private int recordID_ ;
      /**
       * <code>required uint32 recordID = 5;</code>
       */
      public boolean hasRecordID() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 recordID = 5;</code>
       */
      public int getRecordID() {
        return recordID_;
      }
      /**
       * <code>required uint32 recordID = 5;</code>
       */
      public Builder setRecordID(int value) {
        bitField0_ |= 0x00000010;
        recordID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 recordID = 5;</code>
       */
      public Builder clearRecordID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        recordID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object units_ = "";
      /**
       * <code>optional string Units = 6;</code>
       */
      public boolean hasUnits() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string Units = 6;</code>
       */
      public java.lang.String getUnits() {
        java.lang.Object ref = units_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            units_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Units = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUnitsBytes() {
        java.lang.Object ref = units_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          units_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Units = 6;</code>
       */
      public Builder setUnits(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        units_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Units = 6;</code>
       */
      public Builder clearUnits() {
        bitField0_ = (bitField0_ & ~0x00000020);
        units_ = getDefaultInstance().getUnits();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Units = 6;</code>
       */
      public Builder setUnitsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        units_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb_grocery.InventoryDetails)
    }

    static {
      defaultInstance = new InventoryDetails(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb_grocery.InventoryDetails)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_grocery_InventoryDetails_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_grocery_InventoryDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9src/test/resources/SIUE_GroceryStore/p" +
      "b_msg_grocery.proto\022\npb_grocery\"w\n\020Inven" +
      "toryDetails\022\017\n\007StoreID\030\001 \002(\005\022\014\n\004Date\030\002 \002" +
      "(\003\022\023\n\013ProductName\030\003 \002(\t\022\016\n\006Amount\030\004 \002(\r\022" +
      "\020\n\010recordID\030\005 \002(\r\022\r\n\005Units\030\006 \001(\tB>\n$com." +
      "ociweb.pronghorn.stage.generatorB\024PBSpee" +
      "dQueryProviderH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_grocery_InventoryDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_grocery_InventoryDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_grocery_InventoryDetails_descriptor,
        new java.lang.String[] { "StoreID", "Date", "ProductName", "Amount", "RecordID", "Units", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
